"""tentando mais uma vez com postgresql

Revision ID: 0499c023d405
Revises: 
Create Date: 2023-01-20 14:34:59.885045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0499c023d405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('diagnostics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
